const base='https://github.com/achimala/TheLongSilence/blob/69b3296b4b6ecb3ca75ed6193e4b785c4c791c0f/';
const shots={terran:{title:'行星、海洋与云层',desc:'观察行星弧面、海陆颜色、云层、昼夜交界和薄薄的大气。这些外观由生成参数与着色器共同决定。',steps:['打开中文能力体验，等待加载后点击 WAKE。','点击「类地行星」，收起面板观察画面。','点击「扫描目标」，查看扫描数量与档案变化。'],boundary:'场景快捷定位会移动飞船，不代表玩家手动飞到了这里。'},cabin:{title:'可以走进的驾驶舱',desc:'舱内有实际三维结构和可交互驾驶座。外部恒星光通过舷窗形成阴影，舱内灯光和尘埃营造空间感。',steps:['点击「驾驶舱」进入驾驶座。','用 W/S 控制油门，方向键控制转向。','按 E 离座，WASD 行走；V 切换外部视角。'],boundary:'舱内走动采用走廊边界和障碍物碰撞规则，没有通用刚体物理系统。'},rings:{title:'星环不只是贴在背景上的一圈',desc:'观察巨行星条带、星环颗粒层次和投影。生成阶段还会调整环面倾角，让光照关系更容易看清。',steps:['点击「星环」，进入有星环的行星附近。','收起面板，观察星环与行星的遮挡。','也可点击「气态巨行星」比较另一种取景角度。'],boundary:'气态巨行星不可着陆；不同星系不保证都有相同类型的行星。'},ground:{title:'从轨道进入可行走的地表',desc:'着陆通过下降动画与云层遮挡切换到独立地表场景。地形、材质、岩石、树木和天空在地面尺度重新组织。',steps:['从首页打开「已验证的地表体验」入口，等待加载后点击 WAKE。','点击「行星着陆」，直接进入低画质地表；再点击「地面步行」。','切换太空场景会通过直接起飞辅助路径返回太空。'],boundary:'此截图来自 q=low 与 groundfast=1。普通着陆交接未确认成功，诊断入口跳过下降动画和预编译等待。'},map:{title:'星图把探索变成有方向的旅程',desc:'导航星图呈现在舱内全息界面上，选择星系后通过折叠驱动前往。跳跃与探索进度由 Game 管理。',steps:['点击「星图」查看当前可用星系。','按原版提示选择星系并确认跳跃。','按 Esc 退出；打开「探索档案」阅读已扫描目标。'],boundary:'本次验证星图打开与显示。完整跨星系跳跃及七共振器通关未作为已通过项目。'}};
document.querySelectorAll('[data-shot]').forEach(b=>b.onclick=()=>{const s=shots[b.dataset.shot];document.querySelectorAll('[data-shot]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelector('#scene-image').src=`assets/${b.dataset.shot}.png`;document.querySelector('#scene-image').alt=s.title+'：本机实测截图';document.querySelector('#scene-title').textContent=s.title;document.querySelector('#scene-description').textContent=s.desc;document.querySelector('#scene-steps').replaceChildren(...s.steps.map(t=>{const li=document.createElement('li');li.textContent=t;return li;}));document.querySelector('#scene-boundary').textContent=s.boundary;document.querySelector('#scene-caption').textContent=b.dataset.shot==='ground'?'低画质 + 直接地表诊断实测；跳过正常下降和预编译等待。':b.dataset.shot==='map'?'原版全息星图 · q=low 低画质实测。':'本机原版渲染截图，含本研究新增的能力面板；不代表所有设备的运行效果。';});
const stages={seed:['种子 → 可重复的宇宙','mulberry32 伪随机数发生器，把一个整数转成稳定的随机序列。按恒星类型权重、轨道规则和行星参数模板生成世界；再加入起始星系宜居等人工约束。保存种子与探索状态，就能重建同一版本的世界。更改规则或随机调用顺序可能改变结果，因此未来存档需要生成器版本号。','src/world/generate.js'],bake:['复杂表面 → 可以重复读取的数据','多层噪声决定行星高度和颜色，先写入立方体贴图，后续帧读取贴图再计算法线与光照。几何按材质合并，重复模型采用实例或共享资源。地面材质、模型也有提前离线制作的部分。核心思想是让重复计算只发生在必要的时候。','src/gfx/cubeBake.js'],scene:['千万公里的太空 → 脚下的米制地面','太空使用相对飞船的坐标和对数深度，降低远近尺度差异导致的抖动与遮挡错误。着陆准备独立地面场景，以米为单位，构建径向地形网格和实例植被。下降云层遮挡场景交接，保持视觉连续。','src/game/Game.js'],light:['几何与材质 → 最终画面','GPU 着色器计算大气散射、星体表面、体积光与阴影。后处理完成曝光适应、泛光、镜头效果、色调映射和抗锯齿。引擎再按帧耗时调整分辨率。高质量画面会消耗显卡带宽与着色器时间，帧率目标不是保证。','src/gfx/PostFX.js']};
function stage(k){const [title,body,file]=stages[k];const node=document.querySelector('#stage-detail');node.replaceChildren();const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.textContent=body;const a=document.createElement('a');a.href=base+file;a.target='_blank';a.rel='noopener';a.textContent='查看实现：'+file+' ↗';node.append(h,p,a);}
document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-stage]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));stage(b.dataset.stage);});stage('seed');
const paths=[['first','P1 / 体验完善','存档与继续探索','让探索变成可以持续进行的旅程。',['复用：种子、发现集合、剧情与飞船状态','补充：存档版本、恢复顺序、升级迁移与导入导出'],'复杂度：中 · 先做本机 IndexedDB 存档'],['first','P1 / 体验完善','中文化与新手导览','减少玩家从舱内起步到第一次扫描的理解成本。',['复用：HUD、指令系统与原版交互','补充：文本资源表、术语、键位冲突与指引'],'复杂度：低至中 · 本研究已提供独立快捷面板'],['first','P1 / 性能工程','可选画质与设备分档','让更多电脑在可接受画质下运行。',['复用：动态分辨率与诊断开关','补充：纹理档位、后处理开关、显存预算与基准场景'],'复杂度：中 · 移动端仍需专项重构'],['product','P2 / 内容产品','科幻展览与自动导览','把场景、镜头和知识讲解组织成可重复演示。',['复用：Director、pose、inspect 与星图','补充：章节、讲解音轨、演示循环和无人值守恢复'],'复杂度：中 · 适合先做浏览器展陈'],['product','P2 / 教学工具','行星参数实验室','让用户理解大气、光照角度和地形参数如何改变外观。',['复用：生成参数、材质与着色器','补充：参数控件、重新烘焙、前后对比与科学解释'],'复杂度：中 · 科学准确性要单独验证'],['product','P2 / 游戏内容','任务、资源与探索日志','在视觉探索之上增加明确的游玩目标。',['复用：扫描、遭遇、升级和叙事触发','补充：任务数据结构、经济规则、平衡与保存'],'复杂度：中至高 · 先做一个完整任务闭环'],['advanced','P3 / 架构演进','多人协作探索','共享位置、发现和任务进度。',['复用：确定性生成器可降低静态世界同步量','补充：服务端权威、状态同步、重连、冲突与反作弊'],'复杂度：高 · 同种子并不能解决动态状态同步'],['advanced','P3 / 可选 AI','带依据的船载助手','让助手解释已发现的世界或协助选择路线。',['复用：档案、世界参数与当前状态','补充：检索上下文、模型服务、费用与内容约束'],'复杂度：中至高 · 原版未提供运行时大模型'],['advanced','P3 / 引擎研发','连续地形与更大世界','进一步缩小太空与地面之间的系统割裂。',['复用：共享地形规则、深度与场景管理经验','补充：连续 LOD、区块流送、碰撞及 GPU 资源调度'],'复杂度：很高 · 属于引擎级改造']];
for(const [kind,priority,title,desc,items,cost] of paths){const a=document.createElement('article');a.dataset.kind=kind;a.innerHTML=`<small>${priority}</small><h3>${title}</h3><p>${desc}</p><ul>${items.map(x=>`<li>${x}</li>`).join('')}</ul><p class="cost">${cost}</p>`;document.querySelector('#roadmap-cards').append(a);}
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelectorAll('[data-kind]').forEach(x=>x.hidden=b.dataset.filter!=='all'&&x.dataset.kind!==b.dataset.filter);});
const typeNames={terran:'类地',gas:'气态',desert:'沙漠',barren:'荒芜',ice:'冰冻',toxic:'有毒',iron:'富铁',lava:'熔岩',ocean:'海洋'};
fetch('universe.json').then(r=>{if(!r.ok)throw Error('目录加载失败');return r.json();}).then(data=>{const select=document.querySelector('#system-select');data.systems.forEach((s,i)=>select.add(new Option(`${String(i+1).padStart(2,'0')} · ${s.name}`,i)));const show=()=>{const s=data.systems[Number(select.value)];document.querySelector('#system-summary').textContent=`${s.planets.length} 颗行星 · ${s.planets.reduce((n,p)=>n+p.moons,0)} 颗卫星`;document.querySelector('#planet-list').replaceChildren(...s.planets.map(p=>{const d=document.createElement('div');d.className='planet';const b=document.createElement('b');b.textContent=p.name;const t=document.createElement('span');t.textContent=`${typeNames[p.type]||p.type} · ${p.moons} 颗卫星${p.rings?' · 星环':''}`;d.append(b,t);return d;}));};select.onchange=show;show();}).catch(e=>document.querySelector('#system-summary').textContent=e.message);
// No cross-origin localhost probe on a public website: users launch intentionally.
if(['localhost','127.0.0.1'].includes(location.hostname))document.querySelector('.local-links').hidden=false;
if(location.hash==='#local-run')document.querySelector('#local-run').open=true;
document.querySelectorAll('a[href="#local-run"]').forEach(a=>a.addEventListener('click',()=>{document.querySelector('#local-run').open=true;}));
