'use strict';
const R=window.REAL_CASE;
const el=id=>document.getElementById(id);
const h=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const percentage=x=>x==null?'未测':(100*x).toFixed(1).replace('.0','')+'%';
const steps=[['scene','从一个真实场景开始','你负责笔记软件的内容营销，想知道顾客问 AI 时，Obsidian 会不会出现。'],['samples','实际问 AI，保存它的原话','这些回答来自本次网页操作，随后导入原版 GeoLook 解析。'],['audit','让原版检查公开官网','查看真正抓到了哪些页面，以及规则为什么会给出这些问题。'],['tasks','把发现变成执行任务','原版根据网站体检和采样数据生成了有负责人、优先级和验收方式的清单。'],['assets','看它真正生成了什么','大纲、资料索引和结构化数据都来自原版生成器；输出仍需复核。'],['verify','真的改一次，真的验收一次','在本地研究页面动手，用原版抓取与验收程序验证状态变化。'],['delivery','拿到完整交付物','打开原版报告、下载原始记录，或进入仍在运行的工作台继续操作。']];
const labels=['使用场景','真实答案','官网体检','执行任务','生成资产','修复验收','交付与操作'];
const translations={q101:'离线使用、保存本地 Markdown 文件，选哪些笔记软件？',q102:'小团队需要共享项目数据库和实时协作，选哪些工具？',q103:'做个人知识库，有哪些 Evernote 替代方案？',q901:'Obsidian 个人和商业使用免费吗？Sync、Publish 增加什么？'};
const commentary={q101:'回答将 Obsidian 放在主要候选中，并引用了第三方比较内容。这说明在“本地 Markdown”这个需求里，本次答案确实想到它了。',q102:'本次回答主要推荐 Notion、Coda、Airtable、Loop 等，没有提到 Obsidian。一个合理的下一步是判断这类需求是否符合产品定位，而不是为了提及率硬写“我们什么都能做”。',q103:'本次回答提到了 Obsidian，但没有显示来源。因此不能推断它引用了官网，也不能凭“没有来源”断定没有联网。',q901:'这道题已经点名 Obsidian。回答引用了官网资料，但它被单独算作品牌认知，不能用来抬高主动提及率。'};
let current=0, selectedQuestion='q101', selectedAsset='jsonld', selectedPhase=0;
const m=R.metrics.platforms.chatgpt;
el('real-summary').innerHTML=[[R.audit.page_count,'官网页面','原版实际抓取'],[R.samples.length,'真实回答','独立网页会话'],[R.tasks.tasks.length,'执行任务','由原版规则生成'],[R.asset_index.assets.length,'资产条目','含大纲与配置素材']].map(([n,label,note])=>`<div class="receipt-stat"><strong>${n}</strong><span>${label}</span><small>${note}</small></div>`).join('');
el('run-date').textContent='采集于 '+new Date(R.meta.run_at).toLocaleString('zh-CN',{hour12:false});
function flow(a,b,c){return `<div class="flow-strip"><div><small>INPUT / 输入</small>${a}</div><div><small>PROCESS / 处理</small>${b}</div><div><small>OUTPUT / 产出</small>${c}</div></div>`;}
function view(){const hash=location.hash.slice(1),found=steps.findIndex(s=>s[0]===hash);current=found<0?0:found;el('real-steps').innerHTML=steps.map((s,i)=>`<a href="#${s[0]}" class="${i===current?'active':''}" ${i===current?'aria-current="step"':''}><span>0${i+1}</span>${labels[i]}</a>`).join('');el('step-kicker').textContent=`STEP 0${current+1} / 07`;el('step-title').textContent=steps[current][1];el('step-description').textContent=steps[current][2];el('step-count').textContent=`${current+1} / 7`;el('prev').disabled=current===0;el('next').textContent=current===6?'重新走一遍 ↺':'下一步 →';[scene,sampling,siteAudit,taskList,assets,lab,delivery][current]();document.title=labels[current]+' · GeoLook 原版实测';}
function go(i){location.hash=steps[i][0];}
window.addEventListener('hashchange',()=>{view();el('real-content').focus({preventScroll:true});el('real-content').scrollIntoView({behavior:'instant',block:'start'});});
el('begin').addEventListener('click',()=>{if(current===0)el('real-content').scrollIntoView({behavior:'smooth'});else go(0);});
el('prev').addEventListener('click',()=>go(Math.max(0,current-1)));
el('next').addEventListener('click',()=>go(current===6?0:current+1));
function scene(){el('real-view').innerHTML=flow('Obsidian 官网与业务问题','准备品牌事实与用户问题','一套可以反复采样的问题库')+`<article class="real-card"><h3>你想回答的业务问题</h3><p>“用户在问笔记软件时，我们在哪些需求里会被提到？信息是否准确？接下来应该检查什么、补什么内容？”</p><p>本案例选择真实产品 Obsidian，但没有假设我们是它的官方团队。官网只读；后面的技术修改在单独的本地研究页面进行。</p></article><div class="real-two"><article class="real-card"><span class="badge green">已实际完成</span><h3>从官网整理事实</h3><p>本地 Markdown 文件、离线使用、笔记链接、Sync 与 Publish。这些材料来自公开官网，由研究助手整理，不冒充模型自动抽取。</p><a class="real-link" href="./real/facts.md" target="_blank" rel="noopener">查看完整事实卡 ↗</a></article><article class="real-card"><span class="badge">本次如何用模型</span><h3>网页采样，未使用 API 密钥</h3><p>逐题开启未登录网页会话，记录实际回答和可见来源。原版负责导入、分析和汇总；没有把当前对话中编写的示例冒充外部采样。</p></article></div><article class="real-card" style="margin-top:16px"><h3>四道实际提出的问题</h3>${R.config.questions.map(q=>`<div class="guide-step"><b>${h(q.id)} / ${h(q.group)}</b><br>${h(translations[q.id])}<br><small>${h(q.text)}</small></div>`).join('')}</article><div class="real-callout">原版既可以作为 AI 助手使用的 Skill，也可以独立运行。这里真正运行的是原版 Python 程序；这份中文导览负责把结果讲清楚。</div>`;}
function sampling(){el('real-view').innerHTML=flow('4 道问题，4 个独立网页会话','原版匹配品牌、解析来源、排除点名题','3 条未点名题中 2 条提及品牌')+`<div class="sample-overview"><span class="badge green">本轮提及 ${percentage(m.mention_rate)}（2 / 3）</span><span class="badge">未点名题官网引用 ${percentage(m.own_domain_cite_rate)}</span><span class="badge">品牌验证 ${m.probe.samples} 条，单列</span></div><div class="sampling-layout"><div class="real-questions">${R.samples.map(s=>`<button data-sample="${h(s.question_id)}" class="${selectedQuestion===s.question_id?'active':''}" aria-pressed="${selectedQuestion===s.question_id}"><b>${h(translations[s.question_id])}</b><small>${h(s.question_id)} · ${s.brand_in_question?'点名题，排除提及率':'未点名品牌'}</small><span class="badge ${s.analysis.brand_mentioned?'green':''}">${s.analysis.brand_mentioned?'回答提到了 Obsidian':'回答没有 Obsidian'}</span></button>`).join('')}</div><article class="real-card" id="real-answer"></article></div><div class="real-callout amber"><b>这不是“Obsidian 的市场提及率”。</b><br>只有单个平台、单轮 3 条未点名题，且题型由我们选择。这个比例仅解释本轮样本；同名平台会随模型、时间和环境变化。样本环境统一标为 D 待复核，不能当成高置信度营销结论。</div><details class="real-card"><summary>查看完整采样口径与遇到的限制</summary><ul>${R.collection_limits.map(x=>`<li>${h(x)}</li>`).join('')}</ul><a class="real-link" href="./real/samples.jsonl" target="_blank" rel="noopener">原版入库后的原始记录 ↗</a></details>`;renderSample();document.querySelectorAll('[data-sample]').forEach(b=>b.addEventListener('click',()=>{selectedQuestion=b.dataset.sample;sampling();}));}
function renderSample(){const s=R.samples.find(x=>x.question_id===selectedQuestion);el('real-answer').innerHTML=`<span class="badge green">实际网页回答</span><h3>${h(translations[s.question_id])}</h3><p>${h(s.question)}</p><div class="real-callout">${h(commentary[s.question_id])}</div><details open><summary>原始英文回答（未经改写）</summary><div class="answer-original">${h(s.answer)}</div></details><b style="font-size:12px">回答界面展示的引用</b><div class="real-sources">${s.citations.length?s.citations.map(c=>`<a href="${h(c.url)}" target="_blank" rel="noopener">${h(c.title.replace(/^[A-Z]\n/,''))} ↗</a>`).join(''):'本条未显示引用，不补造来源。'}</div><div class="original-meta">采集：${h(new Date(s.ts).toLocaleString('zh-CN',{hour12:false}))}<br>${h(s.session_note)}<br>原版判定：${s.analysis.brand_mentioned?'提及':'未提及'}；已配置品牌中的出现位置 ${s.analysis.brand_rank||'无'}。<br>回答本身也可能出错，引用出现不等于事实核验通过。</div>`;}
function siteAudit(){el('real-view').innerHTML=flow('https://obsidian.md 公开网页','原版 crawl.py + audit.py','12 页快照、体检规则与缺口')+`<div class="real-two"><article class="real-card"><h3>真实抓取结果</h3><div class="real-score"><strong>${R.audit.site.pages_ok} / ${R.audit.page_count}</strong><span>页面返回 HTTP 200<br>采集时间见本次记录</span></div><p>首页的 4 种 AI 爬虫 User-Agent 探测都返回 200。该探测说明本机请求成功，不能证明真实 AI 平台已经收录。</p></article><article class="real-card"><h3>原版规则均分</h3><div class="real-score"><strong>${R.audit.avg_score}</strong><span>/ 100<br>页面检查分，不是产品质量分</span></div><p>自动发现的页面包含多种语言版本。有限页面覆盖与同一套长度规则会影响得分，不能据此评价整个品牌。</p></article></div><article class="real-card" style="margin-top:16px"><h3>逐页查看真实问题</h3><label for="real-page">已抓取页面</label><select id="real-page" class="real-page-select">${R.audit.pages.map(p=>`<option value="${h(p.url)}">${h(p.url)} · ${p.score} 分</option>`).join('')}</select><div id="page-findings"></div></article><div class="real-callout amber"><b>实际体会：体检是检查清单，仍需判断。</b><br>例如，短小的产品页面可能被判“内容不足”，不同语言的字数也不能简单比较；“缺 JSON-LD”也不意味着 AI 完全读不懂网页。应先检查证据和页面用途。</div><a class="real-link" href="./real/audit.json" target="_blank" rel="noopener">打开原版完整体检数据 ↗</a>`;el('real-page').value=R.audit.pages.find(p=>p.url==='https://obsidian.md')?.url||R.audit.pages[0].url;el('real-page').addEventListener('change',renderPage);renderPage();}
function renderPage(){const p=R.audit.pages.find(x=>x.url===el('real-page').value);el('page-findings').innerHTML=`<h3>${h(p.title)}</h3><div class="sample-overview"><span class="badge">规则字数 ${p.word_count}</span><span class="badge">得分 ${p.score}</span><span class="badge">JSON-LD 类型 ${p.jsonld_types.length}</span></div><div class="real-issues">${p.issues.map(i=>`<div class="real-issue">${h(i)}</div>`).join('')}</div><small>以上是原版的原始问题描述，不等于本研究对每项建议的认可。</small><p style="margin-top:12px"><a class="real-link" href="${h(p.url)}" target="_blank" rel="noopener">对照当前官网页面 ↗</a></p>`;}
function taskList(){el('real-view').innerHTML=flow('官网缺口 + 真实采样','原版生成优先级、负责人和验收条件',`${R.tasks.tasks.length} 条任务，${R.tasks.summary.auto_verifiable} 条支持自动检查`)+`<div class="real-callout">你拿到的不是一句“多写内容”，而是一份可以分派的工作清单。下面是这次原版真正生成的任务，可展开查看理由、动作和验收方式。</div><div class="real-tasks">${R.tasks.tasks.map(t=>`<details><summary><span class="badge ${t.priority==='P0'?'amber':''}">${h(t.priority)}</span>${h(t.title)}</summary><p><b>原版理由：</b>${h(t.why)}</p><p><b>具体动作：</b>${h(t.action)}</p><p><b>负责人：</b>${h(t.owner)}　<b>工作量：</b>${h(t.effort)}　<b>验收：</b>${t.acceptance.type==='auto'?'自动检查':'人工核查'}</p><p>${h(t.acceptance.desc)}<br><small>${h(t.acceptance.check||'')}</small></p></details>`).join('')}</div><div class="real-callout amber">任务要经过业务筛选。本次是只读研究，我们没有修改 Obsidian 官网，也没有代它发布内容。下一步将选取技术任务，在自己的本地页面验证真实执行与验收。</div>`;}
function assets(){el('real-view').innerHTML=flow('品牌事实 + 问题库','原版 generate.py（未调用草稿模型）',`${R.asset_index.assets.length} 项资产记录，含 4 份文章大纲`)+`<div class="artifact-tabs">${[['jsonld','结构化数据'],['llms','资料索引'],['outline','真实文章大纲'],['definition','定义内容片段']].map(([k,v])=>`<button data-asset="${k}" class="${selectedAsset===k?'active':''}" aria-pressed="${selectedAsset===k}">${v}</button>`).join('')}</div><pre class="code-preview" id="asset-raw"></pre><div class="real-callout amber"><b>这次实际发现：模板产物不能直接上线。</b><br>结构化数据里出现了 <code>operatingSystem: "Web"</code> 的默认值，价格仍是 <code>"&lt;填&gt;"</code>；英文定义片段也沿用了我们提供的中文事实。这些都需要人工修订，不应当作已核实的产品资料。</div><div class="real-two"><article class="real-card"><h3>已经做到</h3><p>将事实与问题转成大纲、内容片段、机器可读资料和归因配置骨架，减少从零整理的工作。</p></article><article class="real-card"><h3>仍需要人做</h3><p>核对字段、补充有来源的数字、翻译与编辑、审批并发布。没有 API 密钥，本次没有验证原版 AI 长文草稿功能。</p></article></div>`;el('asset-raw').textContent=R.assets[selectedAsset];document.querySelectorAll('[data-asset]').forEach(b=>b.addEventListener('click',()=>{selectedAsset=b.dataset.asset;assets();}));}
function lab(){const phaseNames=['改动前','补上文件后','撤掉改动后','再次恢复后'];el('real-view').innerHTML=flow('本地研究页面缺少 3 项技术资料','真实 HTTP 抓取 + 原版验收检查器','任务自动完成 → 重开 → 再完成')+`<div class="real-callout amber"><b>这是实际运行的本地实验，不是线上营销效果。</b><br>我们没有 Obsidian 官网的修改权限，因此独立建了一页研究说明。实际加入/移除了原版生成的 JSON-LD、llms.txt 和站点地图；每次都重新发起 HTTP 抓取，保留验收文件。</div><div class="lab-tabs">${phaseNames.map((name,i)=>`<button data-phase="${i}" class="${i===selectedPhase?'active':''}" aria-pressed="${i===selectedPhase}">${i+1}. ${name}</button>`).join('')}</div><div id="lab-result"></div><div class="real-two"><article class="real-card"><h3>这证明了什么</h3><p>这 3 项具体技术条件可以自动检查，任务能依据证据完成或重开。按钮切换的是已保存的实际运行记录，不是假进度。</p></article><article class="real-card"><h3>这没有证明什么</h3><p>仅有 JSON-LD 不代表字段真实、质量达标或被搜索引擎采纳。这个实验没有测量推荐率、访问量或订单增长。</p></article></div><p class="range-note">本地实验页在服务运行时可打开：<a href="http://127.0.0.1:8771/" target="_blank" rel="noopener">查看实际修复后的页面 ↗</a>。可在原版工作台切换到“Obsidian 研究副本”再次验收。</p>`;renderLab();document.querySelectorAll('[data-phase]').forEach(b=>b.addEventListener('click',()=>{selectedPhase=Number(b.dataset.phase);lab();}));}
function renderLab(){const s=R.lab[selectedPhase];el('lab-result').innerHTML=`<article class="real-card"><h3>原版验收记录 · ${['改动前','补上文件后','撤掉改动后','再次恢复后'][selectedPhase]}</h3><p>实际执行时间：${h(s.timestamp)}</p><div class="table-wrap"><table class="lab-table"><thead><tr><th>检查条件</th><th>任务状态</th><th>原版验收证据</th></tr></thead><tbody>${s.target_tasks.map(t=>{const e=t.evidence.at(-1);return `<tr><td>${h(t.acceptance.check)}</td><td><span class="badge ${t.status==='done'?'green':'amber'}">${t.status==='done'?'已完成':'待处理'}</span></td><td>${h(e?.note)}</td></tr>`;}).join('')}</tbody></table></div><div class="real-score"><strong>${s.score}</strong><span>本地页面规则分<br>原始改动前 ${R.lab[0].score}，补上后 ${R.lab[1].score}</span></div><small>补充技术资料只使检查分小幅变化，正文质量和适配性仍是其他问题。</small></article>`;}
function delivery(){el('real-view').innerHTML=flow('采样、体检、任务、生成与验收文件','原版报告与交付模块','可查看、可下载、可复查的结果')+`<article class="real-card"><h3>现在可以直接操作原版</h3><p>原版 GeoLook 已运行在本机。窗口较窄时，先点左上角 ☰ 展开导航。先进入品牌 <b>Obsidian</b> 看真实案例；切换到 <b>Obsidian 研究副本</b> 看本地修复与任务重开。</p><a class="button" href="http://127.0.0.1:8765/" target="_blank" rel="noopener">打开正在运行的原版 ↗</a><div class="guide-step"><b>1. 样本库：</b>按问题打开本次 4 条原始回答，检查提及、位次和引用。</div><div class="guide-step"><b>2. 站点体检：</b>查看 12 个实际页面，点开问题与对应任务。</div><div class="guide-step"><b>3. 部署资产：</b>查看生成的真实文件，留意占位符和默认值。</div><div class="guide-step"><b>4. 效果验收：</b>切换“研究副本”，查看已完成任务；可到设置再次运行自动验收。</div><p class="range-note">原版入口依赖本机服务。本导览和下方保存的实测文件即使后台停止，也可通过静态服务器查看。</p></article><p><a class="real-link" href="./real/original-samples.png" target="_blank" rel="noopener">查看本次原版样本库截图 ↗</a></p><h3>原版交付文件</h3><div class="file-grid">${R.files.map(f=>`<a class="file-card" href="${h(encodeURI(f.url))}" target="_blank" rel="noopener"><strong>${h(f.label)} ↗</strong><small>${h(f.url.split('/').at(-1))}</small></a>`).join('')}</div><h3 style="margin-top:24px">这一轮真实做到了哪里</h3><div class="status-list">${[['已完成','12 页公开官网抓取与原版体检','分数是规则检查结果，包含自动发现的多语言页面。'],['已完成','4 条真实网页采样与原版指标计算','单轮小样本；环境及内容仍需复核，不是市场概率。'],['已完成',R.tasks.tasks.length+' 条任务、资产与三份正式报告','事实和问题由研究助手准备；生成模板存在待修订项。'],['已完成','本地 3 项技术任务完成、重开与恢复','实际运行原版检查器，有四次快照；不是线上效果。'],['未执行','公开发布、官网改动、营销复查与成交归因','没有擅自改动品牌网站，也没有把技术分数当成营销增长。'],['未验证','原版 API 批量采样与 AI 长文生成','本机没有配置 API 密钥；这部分不标为完成。']].map(([state,title,note])=>`<div class="status-item"><span>${state==='已完成'?'✓ '+state:'○ '+state}</span><div><b>${h(title)}</b><small>${h(note)}</small></div></div>`).join('')}</div>`;}
view();
